preset: symfony

enabled:
  - align_phpdoc
  - alpha_ordered_imports
  - array_indentation
  - const_visibility_required
  - phpdoc_order

disabled:
  - no_superfluous_phpdoc_tags_symfony
  - phpdoc_to_comment
  - phpdoc_var_without_name
